### ISSUE TITLE
Building process

### ISSUE THREAD

**Issue by ugintl** [thanhminh2005/B2B-eCommerce-platform-for-wholesalers-and-distributors#65]
How to build/compile this app on windows?

Is it crosss platform?

**Comment by thanhminh2005** [comment]
This repo is just my home work for university it not fully working yet and I have hide the appsettings file which is without it you cannot build this app if you not change the dependency of them.
I'm sorry this repo is supposed to be private and forgot to change.
But to answer your question this is a .NET core web Api which is cross platform.

**Comment by ugintl** [comment]
@thanhminh2005 How do you build such app anyway? For learning purpose. What tools I would need?
